### ISSUE TITLE
Cannot create Docker Network

### ISSUE THREAD

**Issue by beavanzi** [grafana/promql-anomaly-detection#1]
Hello! I'm facing the following issue while trying to start the demo.

 ✘ Network opentelemetry-demo  Error                                                                                                                                                   0.0s 
failed to create network opentelemetry-demo: Error response from daemon: all predefined address pools have been fully subnetted
make: *** [Makefile:15: start] Error 1

![Image](https://github.com/user-attachments/assets/d91303f6-a666-4de3-8474-b0c3325519ca)

Could you, please, help me understand what's going on?

**Comment by jcreixell** [comment]
@beavanzi thank you for reporting this issue, this sounds like a wider issue with your docker setup. I would recommend upgrading/reinstalling docker and, if safe to do so, prune your docker environment (for example, via `docker system prune --all`, note this will clear all your current images, containers, networks, volumes, etc, apply at your own discretion).

However, some folks reported issues running the demo (for example, in #2 ) and I just merged some fixes for that. Please let me know if the demo works for you after pulling the latest commits from `main` 🙇

**Comment by jcreixell** [comment]
I will close this issue as stale, @beavanzi feel free to reopen a new one if you are still experiencing this issue 🙇
